In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Bank_Churn.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df.shape

(10000, 14)

In [4]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [5]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [6]:
X = df.iloc[:, 3:13]
y = df['Exited']

In [7]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [8]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [9]:
# Creating Dummy variables
gender = pd.get_dummies(X['Gender'])
geography = pd.get_dummies(X['Geography'])

In [10]:
#Concatenating them back to the dataset
X = pd.concat([X,geography,gender], axis=1)
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  France  Germany  Spain  Female  \
0          1               1        101348.88       1        0      0       1   
1          0               1        112542.58       0        0      1       1   
2          1               0        113931.57       1        0      0       1   
3          0               0         93826.63       1        0      0       1   
4          1               1         79084.10       0        0      1       1   

   Male  
0     0  
1     0  
2     0  
3     0  
4     0

In [11]:
# Removing the Features not required
X = X.drop(['Geography', 'Gender'], axis=1)
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  France  Germany  Spain  Female  Male  
0               1        101348.88       1        0      0       1     0  
1               1        112542.58       0        0      1       1     0  
2               0        113931.57       1        0      0       1     0  
3               0         93826.63       1        0      0       1     0  
4               1         79084.10       0        0      1       1     0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [14]:
X_train

array([[ 1.27754581, -1.23264342, -0.012743  , ..., -0.57138416,
         1.0862028 , -1.0862028 ],
       [-0.49959477,  0.28410615,  0.33282985, ..., -0.57138416,
         1.0862028 , -1.0862028 ],
       [ 0.67827747, -0.09508124, -1.39503438, ..., -0.57138416,
         1.0862028 , -1.0862028 ],
       ...,
       [ 2.06279398, -0.28467494, -0.70388869, ..., -0.57138416,
        -0.9206384 ,  0.9206384 ],
       [-1.02653762,  1.42166833, -0.012743  , ..., -0.57138416,
        -0.9206384 ,  0.9206384 ],
       [ 0.03768029, -1.04304972,  0.67840269, ..., -0.57138416,
         1.0862028 , -1.0862028 ]])

## Creating an ANN 

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.


In [16]:
# Initializing the Network
ann = Sequential()

In [17]:
# Input Layer
ann.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu', input_dim=13))
ann.add(Dropout(0.3))

#Second Layer
ann.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu'))
ann.add(Dropout(0.4))

Instructions for updating:
Colocations handled automatically by placer.


In [18]:
#Creating an output layer
ann.add(Dense(units=1, kernel_initializer='glorot_uniform' , activation='sigmoid'))

In [19]:
ann.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 84        
_________________________________________________________________
dropout_1 (Dropout)          (None, 6)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dropout_2 (Dropout)          (None, 6)                 0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [20]:
#Compiling the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy' , metrics=['accuracy'])

In [21]:
# Fitting the Data
model = ann.fit(X_train, y_train, validation_split=0.33, batch_size=10, epochs=100)

Instructions for updating:
Use tf.cast instead.
Train on 5359 samples, validate on 2641 samples
Epoch 1/100
5359/5359 [==============================] - 3s 535us/step - loss: 1.0672 - accuracy: 0.5589 - val_loss: 0.5726 - val_accuracy: 0.7361
Epoch 2/100
5359/5359 [==============================] - 2s 331us/step - loss: 0.5857 - accuracy: 0.7483 - val_loss: 0.4984 - val_accuracy: 0.8058
Epoch 3/100
5359/5359 [==============================] - 2s 294us/step - loss: 0.5282 - accuracy: 0.7822 - val_loss: 0.4848 - val_accuracy: 0.8023
Epoch 4/100
5359/5359 [==============================] - 2s 284us/step - loss: 0.5103 - accuracy: 0.7921 - val_loss: 0.4776 - val_accuracy: 0.8016
Epoch 5/100
5359/5359 [==============================] - 1s 265us/step - loss: 0.5051 - accuracy: 0.7923 - val_loss: 0.4718 - val_accuracy: 0.8027
Epoch 6/100
5359/5359 [==============================] - 2s 287us/step - loss: 0.4933 - accuracy: 0.7968 - val_loss: 0.4647 - val_accuracy: 0.8058
Epoch 7/100
5359/5359 

5359/5359 [==============================] - 2s 342us/step - loss: 0.4215 - accuracy: 0.8291 - val_loss: 0.3592 - val_accuracy: 0.8580
Epoch 55/100
5359/5359 [==============================] - 2s 337us/step - loss: 0.4150 - accuracy: 0.8291 - val_loss: 0.3616 - val_accuracy: 0.8527
Epoch 56/100
5359/5359 [==============================] - 2s 337us/step - loss: 0.4155 - accuracy: 0.8311 - val_loss: 0.3618 - val_accuracy: 0.8512
Epoch 57/100
5359/5359 [==============================] - 2s 328us/step - loss: 0.4140 - accuracy: 0.8296 - val_loss: 0.3635 - val_accuracy: 0.8489
Epoch 58/100
5359/5359 [==============================] - 2s 327us/step - loss: 0.4148 - accuracy: 0.8268 - val_loss: 0.3588 - val_accuracy: 0.8519
Epoch 59/100
5359/5359 [==============================] - 2s 337us/step - loss: 0.4175 - accuracy: 0.8313 - val_loss: 0.3569 - val_accuracy: 0.8565
Epoch 60/100
5359/5359 [==============================] - 2s 377us/step - loss: 0.4151 - accuracy: 0.8289 - val_loss: 0.3584 

In [22]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
y_pred[:5]

array([[False],
       [False],
       [False],
       [False],
       [False]])

In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1600,   17],
       [ 276,  107]], dtype=int64)

In [24]:
#Claclulating accuracy score
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.8535